//! SDK-neutral, annotation-driven capture for Parity Lens.

use chrono::{DateTime, SecondsFormat, Utc};
use serde::{Serialize, Serializer};
use serde_json::{Map, Value};
use std::collections::{BTreeMap, HashMap};
use std::future::Future;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant, SystemTime};

pub use parity_lens_trace_macros::{
    trace_data, trace_enum, trace_function, trace_serializable, trace_serializable_impl,
};

/// One annotation-generated function trace.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionTrace {
    pub step_id: &'static str,
    pub function_name: &'static str,
    pub symbols: FunctionTraceSymbols,
    pub span_id: u64,
    pub parent_span_id: Option<u64>,
    pub depth: usize,
    pub sequence: u64,
    pub input: Value,
    pub output: Value,
    pub duration_ms: u128,
    pub is_successful: bool,
}

/// Exact symbols for an annotated function.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionTraceSymbols {
    pub function_symbol: &'static str,
    pub parameters: Vec<TraceParameterSymbol>,
    pub output_type_symbol: &'static str,
    pub fields: Vec<TraceFieldSymbol>,
}

/// One structurally captured field.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TraceFieldSymbol {
    pub direction: &'static str,
    pub path: String,
    pub serialized_path: String,
    pub owner_type_symbol: &'static str,
    pub value_type_symbol: &'static str,
}

/// Structural symbol metadata generated by `#[trace_data]`.
pub trait TraceDataSymbols {
    fn trace_field_symbols(direction: &'static str, root_path: &str) -> Vec<TraceFieldSymbol>;
}

impl<T, E> TraceDataSymbols for Result<T, E>
where
    T: TraceDataSymbols,
{
    fn trace_field_symbols(direction: &'static str, root_path: &str) -> Vec<TraceFieldSymbol> {
        T::trace_field_symbols(direction, root_path)
    }
}

/// One selected function parameter.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TraceParameterSymbol {
    pub name: &'static str,
    pub type_symbol: &'static str,
    pub path: &'static str,
}

/// One enum member emitted by a manually serialized flags type.
#[derive(Serialize)]
pub struct TraceEnumMember {
    pub symbol: &'static str,
    pub name: &'static str,
    pub value: i64,
}

/// Implement the Parity Lens enum JSON contract for a bitflags type.
#[macro_export]
macro_rules! trace_flags {
    ($type:ty; $($member:ident => $display_name:literal),+ $(,)?) => {
        impl serde::Serialize for $type {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer,
            {
                let mut names = Vec::new();
                $(
                    if self.contains(<$type>::$member) {
                        names.push($display_name);
                    }
                )+
                let members = [
                    $(
                        $crate::TraceEnumMember {
                            symbol: concat!(module_path!(), "::", stringify!($type), "::", stringify!($member)),
                            name: stringify!($member),
                            value: <$type>::$member.bits() as i64,
                        }
                    ),+
                ];
                let mut state = serde::Serializer::serialize_struct(
                    serializer,
                    stringify!($type),
                    8,
                )?;
                serde::ser::SerializeStruct::serialize_field(&mut state, "enum_id", &Option::<&str>::None)?;
                serde::ser::SerializeStruct::serialize_field(
                    &mut state,
                    "enum_symbol",
                    concat!(module_path!(), "::", stringify!($type)),
                )?;
                serde::ser::SerializeStruct::serialize_field(&mut state, "enum_type", stringify!($type))?;
                serde::ser::SerializeStruct::serialize_field(&mut state, "enum_name", &names.join(", "))?;
                serde::ser::SerializeStruct::serialize_field(&mut state, "enum_value", &self.bits())?;
                serde::ser::SerializeStruct::serialize_field(&mut state, "enum_names", &names)?;
                serde::ser::SerializeStruct::serialize_field(&mut state, "enum_members", &members)?;
                serde::ser::SerializeStruct::serialize_field(&mut state, "enum_flags", &true)?;
                serde::ser::SerializeStruct::end(state)
            }
        }
    };
}

/// Per-capture behavior supplied by the Parity Lens adapter.
#[derive(Clone)]
pub struct TraceOptions {
    success_classifier: Arc<dyn Fn(&Value) -> bool + Send + Sync>,
}

impl TraceOptions {
    #[must_use]
    pub fn new(classifier: impl Fn(&Value) -> bool + Send + Sync + 'static) -> Self {
        Self {
            success_classifier: Arc::new(classifier),
        }
    }
}

impl Default for TraceOptions {
    fn default() -> Self {
        Self::new(|_| true)
    }
}

/// Result and traces produced by one scoped capture.
pub struct TraceCapture<T> {
    pub output: T,
    pub traces: Vec<FunctionTrace>,
}

struct CaptureState {
    options: TraceOptions,
    traces: Vec<FunctionTrace>,
    stack: Vec<u64>,
    next_span_id: u64,
}

tokio::task_local! {
    static CAPTURE_STATE: Arc<Mutex<CaptureState>>;
}

/// Run a future with isolated trace collection in its asynchronous task scope.
pub async fn capture<F>(options: TraceOptions, future: F) -> TraceCapture<F::Output>
where
    F: Future,
{
    let state = Arc::new(Mutex::new(CaptureState {
        options,
        traces: Vec::new(),
        stack: Vec::new(),
        next_span_id: 1,
    }));
    let output = CAPTURE_STATE.scope(Arc::clone(&state), future).await;
    let traces = std::mem::take(&mut state.lock().expect("trace capture state poisoned").traces);
    TraceCapture { output, traces }
}

/// Return whether the current asynchronous scope is collecting traces.
#[doc(hidden)]
pub fn is_enabled() -> bool {
    CAPTURE_STATE.try_with(|_| ()).is_ok()
}

/// Capture an annotation-selected value.
#[doc(hidden)]
pub fn capture_value<T: Serialize + ?Sized>(value: &T) -> Value {
    serde_json::to_value(value)
        .unwrap_or_else(|error| serde_json::json!({ "serialization_error": error.to_string() }))
}

/// Capture an HTTP method without requiring an external Serde implementation.
#[doc(hidden)]
pub fn capture_http_method(value: &http::Method) -> Value {
    Value::String(value.as_str().to_string())
}

/// Build a selected-input JSON object.
#[doc(hidden)]
pub fn capture_inputs(values: &[(&str, Value)]) -> Value {
    Value::Object(
        values
            .iter()
            .map(|(name, value)| ((*name).to_string(), value.clone()))
            .collect::<Map<_, _>>(),
    )
}

/// Trace an annotated asynchronous function when a capture scope is active.
#[doc(hidden)]
pub async fn trace_future<F>(
    step_id: &'static str,
    function_name: &'static str,
    mut symbols: FunctionTraceSymbols,
    input: Value,
    future: F,
) -> F::Output
where
    F: Future,
    F::Output: Serialize + TraceDataSymbols,
{
    if !is_enabled() {
        return future.await;
    }

    symbols.output_type_symbol = std::any::type_name::<F::Output>();
    symbols.fields = F::Output::trace_field_symbols("output", "$");
    let (span_id, parent_span_id, depth) = CAPTURE_STATE.with(|state| {
        let mut state = state.lock().expect("trace capture state poisoned");
        let span_id = state.next_span_id;
        state.next_span_id += 1;
        let parent = state.stack.last().copied();
        let depth = state.stack.len();
        state.stack.push(span_id);
        (span_id, parent, depth)
    });
    let started = Instant::now();
    let output = future.await;
    let output_value = capture_value(&output);
    CAPTURE_STATE.with(|state| {
        let mut state = state.lock().expect("trace capture state poisoned");
        let _ = state.stack.pop();
        let is_successful = (state.options.success_classifier)(&output_value);
        state.traces.push(FunctionTrace {
            step_id,
            function_name,
            symbols,
            span_id,
            parent_span_id,
            depth,
            sequence: span_id,
            input,
            output: output_value,
            duration_ms: started.elapsed().as_millis(),
            is_successful,
        });
    });
    output
}

#[doc(hidden)]
pub fn serialize_duration<S: Serializer>(
    value: &Duration,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    serializer.serialize_f64((value.as_secs_f64() * 100_000.0).round() / 100.0)
}

#[doc(hidden)]
pub fn serialize_system_time<S: Serializer>(
    value: &SystemTime,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    serializer
        .serialize_str(&DateTime::<Utc>::from(*value).to_rfc3339_opts(SecondsFormat::Millis, true))
}

#[doc(hidden)]
pub fn serialize_headers<S: Serializer>(
    value: &http::HeaderMap,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    headers_value(value).serialize(serializer)
}

#[doc(hidden)]
pub fn serialize_method<S: Serializer>(
    value: &http::Method,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    serializer.serialize_str(value.as_str())
}

#[doc(hidden)]
pub fn serialize_status<S: Serializer>(
    value: &http::StatusCode,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    serializer.serialize_u16(value.as_u16())
}

#[doc(hidden)]
pub fn serialize_version<S: Serializer>(
    value: &http::Version,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    serializer.serialize_str(&format!("{value:?}"))
}

#[doc(hidden)]
pub fn serialize_optional_body<S: Serializer>(
    value: &Option<bytes::Bytes>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    value
        .as_ref()
        .map(|body| {
            serde_json::from_slice(body)
                .unwrap_or_else(|_| Value::String(String::from_utf8_lossy(body).into_owned()))
        })
        .serialize(serializer)
}

#[doc(hidden)]
pub fn serialize_body<S: Serializer>(value: &[u8], serializer: S) -> Result<S::Ok, S::Error> {
    serde_json::from_slice(value)
        .unwrap_or_else(|_| Value::String(String::from_utf8_lossy(value).into_owned()))
        .serialize(serializer)
}

#[doc(hidden)]
pub fn serialize_redacted<T, S: Serializer>(
    value: &Option<T>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    value.as_ref().map(|_| "[REDACTED]").serialize(serializer)
}

#[doc(hidden)]
pub fn serialize_string_headers<S: Serializer>(
    value: &HashMap<Box<str>, Box<str>>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    let headers = value
        .iter()
        .map(|(name, value)| {
            let name = name.to_ascii_lowercase();
            let value = if matches!(
                name.as_str(),
                "authorization" | "proxy-authorization" | "cookie" | "set-cookie"
            ) {
                "[REDACTED]".to_string()
            } else {
                value.to_string()
            };
            (name, value)
        })
        .collect::<BTreeMap<_, _>>();
    headers.serialize(serializer)
}

fn headers_value(headers: &http::HeaderMap) -> Value {
    let mut grouped: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (name, value) in headers {
        let name = name.as_str().to_ascii_lowercase();
        let value = if matches!(
            name.as_str(),
            "authorization" | "proxy-authorization" | "cookie" | "set-cookie"
        ) {
            "[REDACTED]".to_string()
        } else {
            value.to_str().unwrap_or("<non-utf8>").to_string()
        };
        grouped.entry(name).or_default().push(value);
    }
    Value::Object(
        grouped
            .into_iter()
            .map(|(name, mut values)| {
                let value = if values.len() == 1 {
                    Value::String(values.pop().unwrap_or_default())
                } else {
                    Value::Array(values.into_iter().map(Value::String).collect())
                };
                (name, value)
            })
            .collect(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Serialize)]
    struct TestOutput {
        is_successful: bool,
    }

    impl TraceDataSymbols for TestOutput {
        fn trace_field_symbols(
            _direction: &'static str,
            _root_path: &str,
        ) -> Vec<TraceFieldSymbol> {
            Vec::new()
        }
    }

    fn symbols(function_symbol: &'static str) -> FunctionTraceSymbols {
        FunctionTraceSymbols {
            function_symbol,
            parameters: Vec::new(),
            output_type_symbol: "",
            fields: Vec::new(),
        }
    }

    #[tokio::test]
    async fn scoped_capture_records_parenting_and_does_not_leak() {
        let capture = capture(
            TraceOptions::new(|value| value["is_successful"].as_bool().unwrap_or_default()),
            trace_future(
                "root",
                "test::root",
                symbols("test::root"),
                serde_json::json!({}),
                async {
                    trace_future(
                        "child",
                        "test::child",
                        symbols("test::child"),
                        serde_json::json!({}),
                        async {
                            TestOutput {
                                is_successful: false,
                            }
                        },
                    )
                    .await;
                    TestOutput {
                        is_successful: true,
                    }
                },
            ),
        )
        .await;

        assert_eq!(capture.traces.len(), 2);
        let root = capture
            .traces
            .iter()
            .find(|trace| trace.step_id == "root")
            .expect("root trace");
        let child = capture
            .traces
            .iter()
            .find(|trace| trace.step_id == "child")
            .expect("child trace");
        assert_eq!(child.parent_span_id, Some(root.span_id));
        assert_eq!(child.depth, 1);
        assert!(!child.is_successful);
        assert!(!is_enabled());
    }
}
