[package]
name = "parity_lens_trace"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
bytes = "1"
chrono = "0.4"
http = "1"
parity_lens_trace_macros = { path = "../parity_lens_trace_macros" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt"] }
