namespace ParityLens.TraceInstrumentation;

/// <summary>Receives traces generated by annotated function calls.</summary>
public interface IParityFunctionTraceSink
{
    /// <summary>Records one completed function call.</summary>
    void OnFunctionTrace(ParityFunctionTrace trace);
}
